version: '3'
services:
  mybunkerized:
    image: bunkerity/bunkerized-nginx
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - /docker/storage/infra/bunkerized/bunkerized-hello/www:/www:ro
      - /docker/storage/infra/bunkerized/bunkerized-hello/certs:/etc/letsencrypt
    environment:
      - SERVER_NAME=hello.sol-calc.com
      - AUTO_LETS_ENCRYPT=yes